title: John Doe # your name (or website title) here
logo: "pngtree-original-cartoon-hand-drawn-office-staff-png-image_7123653-removebg-preview.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  University of Waterloo 
  <br><br>
  System Design Engineering 
  <br><br>
  <a href="https://www.linkedin.com/in/ruiyang-li-82967b1b6">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
